// <auto-generated />
using System;
using Kiriha.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kiriha.Services.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430184034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Kiriha.Models.AnimeItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AiredSourcePriority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aired_source_priority");

                    b.Property<DateTime?>("AiringDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("airing_date");

                    b.Property<string>("AlternativeTitles")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("alternative_titles");

                    b.Property<string>("BroadcastDay")
                        .HasColumnType("TEXT")
                        .HasColumnName("broadcast_day");

                    b.Property<string>("BroadcastTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("broadcast_time");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_completed");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_started");

                    b.Property<string>("EnglishTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("english_title");

                    b.Property<int>("EpisodesAired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episodes_aired");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("genres");

                    b.Property<bool>("IsRewatching")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_rewatching");

                    b.Property<string>("JapaneseTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("japanese_title");

                    b.Property<DateTime?>("LastEpisodeAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_episode_at");

                    b.Property<DateTime?>("LastEpisodesSync")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_episodes_sync");

                    b.Property<string>("LocalPosterPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("local_poster_path");

                    b.Property<string>("MainPictureUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("main_picture_url");

                    b.Property<string>("MeanScore")
                        .HasColumnType("TEXT")
                        .HasColumnName("mean_score");

                    b.Property<DateTime?>("NextEpisodeAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_episode_at");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Nsfw")
                        .HasColumnType("TEXT")
                        .HasColumnName("nsfw");

                    b.Property<int>("Popularity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("popularity");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER")
                        .HasColumnName("progress");

                    b.Property<int?>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT")
                        .HasColumnName("rating");

                    b.Property<int>("RewatchCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rewatch_count");

                    b.Property<string>("RussianSynopsis")
                        .HasColumnType("TEXT")
                        .HasColumnName("russian_synopsis");

                    b.Property<string>("RussianTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("russian_title");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("score");

                    b.Property<string>("StartSeason")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_season");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_year");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StatusDetailed")
                        .HasColumnType("TEXT")
                        .HasColumnName("status_detailed");

                    b.Property<string>("Studios")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("studios");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT")
                        .HasColumnName("synopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_episodes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RussianTitle")
                        .HasDatabaseName("idx_user_anime_russian_title");

                    b.ToTable("user_anime", (string)null);
                });

            modelBuilder.Entity("Kiriha.Models.Api.ShikiMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description")
                        .HasJsonPropertyName("description");

                    b.Property<int?>("Episodes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episodes")
                        .HasJsonPropertyName("episodes");

                    b.Property<int?>("EpisodesAired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episodes_aired")
                        .HasJsonPropertyName("episodes_aired");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.Property<DateTime?>("NextEpisodeAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_episode_at")
                        .HasJsonPropertyName("next_episode_at");

                    b.Property<string>("Russian")
                        .HasColumnType("TEXT")
                        .HasColumnName("russian")
                        .HasJsonPropertyName("russian");

                    b.HasKey("Id");

                    b.ToTable("metadata");
                });

            modelBuilder.Entity("Kiriha.Models.Entities.EpisodeListMeta", b =>
                {
                    b.Property<int>("MalId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mal_id");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("fetched_at");

                    b.HasKey("MalId");

                    b.ToTable("episode_list_meta", (string)null);
                });

            modelBuilder.Entity("Kiriha.Models.Entities.EpisodeRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("air_date");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_number");

                    b.Property<int>("MalId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mal_id");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("MalId")
                        .HasDatabaseName("idx_episode_releases_mal_id");

                    b.ToTable("episode_releases", (string)null);
                });

            modelBuilder.Entity("Kiriha.Models.Entities.FileRecognitionCache", b =>
                {
                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_hash");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anime_id");

                    b.Property<string>("LastUsed")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used");

                    b.HasKey("FileHash");

                    b.ToTable("file_recognition_cache");
                });

            modelBuilder.Entity("Kiriha.Models.Entities.HttpCacheEntry", b =>
                {
                    b.Property<string>("UrlHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("url_hash");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT")
                        .HasColumnName("etag");

                    b.Property<string>("LastModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified");

                    b.HasKey("UrlHash");

                    b.ToTable("http_response_cache", (string)null);
                });

            modelBuilder.Entity("Kiriha.Models.Entities.MalSearchCache", b =>
                {
                    b.Property<string>("QueryNormalized")
                        .HasColumnType("TEXT")
                        .HasColumnName("query_normalized");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anime_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<float>("Score")
                        .HasColumnType("REAL")
                        .HasColumnName("score");

                    b.HasKey("QueryNormalized");

                    b.ToTable("mal_search_cache", (string)null);
                });

            modelBuilder.Entity("Kiriha.Models.Entities.SyncTaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anime_id");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<int?>("Progress")
                        .HasColumnType("INTEGER")
                        .HasColumnName("progress");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SuccessfulTrackersJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("successful_trackers_json");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("sync_tasks", (string)null);
                });

            modelBuilder.Entity("Kiriha.Models.HistoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("action_type");

                    b.Property<int>("AnimeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("anime_id");

                    b.Property<string>("AnimeTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("anime_title");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<int>("Episode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode");

                    b.Property<string>("RussianTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("russian_title");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("history", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
