using System;
using Kiriha.Core.Domain.Models;

namespace Kiriha.Mpv.UI.ViewModels.Player;

public partial class PlayerViewModel
{
    partial void OnVideoUrlChanged(string value)
    {
        ResolveAndApplyMetadata(value);
    }

    internal void ResolveAndApplyMetadata(string value)
    {
        OnPropertyChanged(nameof(TrackingTitle));

        if (string.IsNullOrEmpty(value) || _isInitializing) return;

        var resolved = _metadataResolver?.Resolve(value) ?? PlayerMediaMetadata.FromVideoPath(value);

        // If the resolver didn't find an anime in DB, but we already have anime context from a previous file
        // of the same anime series in the same directory, preserve the known titles and anime ID!
        if (resolved.AnimeId is null && _animeId.HasValue && IsSameAnimeSeries(resolved, value))
        {
            resolved = resolved with
            {
                AnimeId = _animeId,
                TitleRu = AnimeTitleRu,
                TitleEn = AnimeTitleEn,
                TitleRomaji = !string.IsNullOrEmpty(AnimeTitleRomaji) ? AnimeTitleRomaji : resolved.TitleRomaji
            };
        }
        _previousVideoUrlForMetadata = value;

        ApplyMetadata(resolved, overwriteAll: true);
        UpdateNavigationAvailability();
    }

    private bool IsSameAnimeSeries(PlayerMediaMetadata newResolved, string newVideoUrl)
    {
        if (string.IsNullOrEmpty(_previousVideoUrlForMetadata) || string.IsNullOrEmpty(newVideoUrl))
            return false;

        var prevDir = System.IO.Path.GetDirectoryName(_previousVideoUrlForMetadata);
        var newDir = System.IO.Path.GetDirectoryName(newVideoUrl);
        if (string.IsNullOrEmpty(prevDir) || !string.Equals(prevDir, newDir, StringComparison.OrdinalIgnoreCase))
            return false;

        var newTitle = !string.IsNullOrWhiteSpace(newResolved.TitleRomaji)
            ? newResolved.TitleRomaji
            : (!string.IsNullOrWhiteSpace(newResolved.TitleRu) ? newResolved.TitleRu : newResolved.OriginalTitle);
        if (string.IsNullOrWhiteSpace(newTitle))
            return false;

        return IsTitleMatch(newTitle, AnimeTitleRomaji) ||
               IsTitleMatch(newTitle, AnimeTitleEn) ||
               IsTitleMatch(newTitle, AnimeTitleRu);
    }

    private static bool IsTitleMatch(string a, string? b)
    {
        if (string.IsNullOrWhiteSpace(b)) return false;
        if (string.Equals(a, b, StringComparison.OrdinalIgnoreCase)) return true;

        var normA = NormalizeTitle(a);
        var normB = NormalizeTitle(b);
        if (string.IsNullOrEmpty(normA) || string.IsNullOrEmpty(normB)) return false;

        return string.Equals(normA, normB, StringComparison.OrdinalIgnoreCase);
    }

    private static string NormalizeTitle(string s)
    {
        var chars = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Where(s, char.IsLetterOrDigit));
        return new string(chars);
    }

    private void ApplyMetadata(PlayerMediaMetadata metadata, bool overwriteAll = false)
    {
        _animeId = metadata.AnimeId ?? (overwriteAll ? null : _animeId);

        if (overwriteAll || !string.IsNullOrWhiteSpace(metadata.OriginalTitle))
            OriginalTitle = metadata.OriginalTitle;

        if (overwriteAll || !string.IsNullOrWhiteSpace(metadata.TitleRu))
            AnimeTitleRu = metadata.TitleRu;

        if (overwriteAll || !string.IsNullOrWhiteSpace(metadata.TitleEn))
            AnimeTitleEn = metadata.TitleEn;

        if (!string.IsNullOrWhiteSpace(metadata.TitleRomaji))
            AnimeTitleRomaji = metadata.TitleRomaji;
        else if (overwriteAll || string.IsNullOrWhiteSpace(AnimeTitleRomaji))
            AnimeTitleRomaji = !string.IsNullOrWhiteSpace(metadata.TitleEn) ? metadata.TitleEn : metadata.TitleRu;

        RawEpisodeText = metadata.EpisodeText;
        EpisodeTitle = string.IsNullOrEmpty(metadata.EpisodeText)
            ? string.Empty
            : $"\u0421\u0435\u0440\u0438\u044F {metadata.EpisodeText}";
        AnimeTitle = !string.IsNullOrWhiteSpace(AnimeTitleRu) ? AnimeTitleRu : AnimeTitleRomaji;

        OnPropertyChanged(nameof(TopTitle));
        OnPropertyChanged(nameof(BottomTitle));
        OnPropertyChanged(nameof(HasBottomTitle));
        OnPropertyChanged(nameof(EpisodeTitle));
        OnPropertyChanged(nameof(HasEpisodeAndBottom));
        OnPropertyChanged(nameof(TrackingTitle));
    }

    public void ApplyExternalMetadata(PlayerMediaMetadata metadata)
    {
        ApplyMetadata(metadata, overwriteAll: false);
        // Do not call _statePublisher.Publish() here: metadata was received from the tracking
        // coordinator, not generated by player playback changes. Echoing it back creates an
        // IPC ping-pong loop between player and tracking service.
    }

    public bool MatchesOriginalTitle(string originalTitle)
    {
        if (string.IsNullOrWhiteSpace(originalTitle))
            return false;

        var current = System.IO.Path.GetFileNameWithoutExtension(VideoUrl);
        if (string.Equals(current, originalTitle, StringComparison.OrdinalIgnoreCase))
            return true;

        if (!string.IsNullOrWhiteSpace(OriginalTitle) && string.Equals(OriginalTitle, originalTitle, StringComparison.OrdinalIgnoreCase))
            return true;

        if (!string.IsNullOrWhiteSpace(AnimeTitleRomaji) && string.Equals(AnimeTitleRomaji, originalTitle, StringComparison.OrdinalIgnoreCase))
            return true;

        if (!string.IsNullOrWhiteSpace(AnimeTitle) && string.Equals(AnimeTitle, originalTitle, StringComparison.OrdinalIgnoreCase))
            return true;

        if (!string.IsNullOrWhiteSpace(AnimeTitleRu) && string.Equals(AnimeTitleRu, originalTitle, StringComparison.OrdinalIgnoreCase))
            return true;

        if (!string.IsNullOrWhiteSpace(AnimeTitleEn) && string.Equals(AnimeTitleEn, originalTitle, StringComparison.OrdinalIgnoreCase))
            return true;

        if (IsTitleMatch(current, originalTitle))
            return true;

        if (!string.IsNullOrWhiteSpace(OriginalTitle) && IsTitleMatch(OriginalTitle, originalTitle))
            return true;

        if (!string.IsNullOrWhiteSpace(AnimeTitleRomaji) && IsTitleMatch(AnimeTitleRomaji, originalTitle))
            return true;

        if (!string.IsNullOrEmpty(current) && current.Length >= 4 && originalTitle.Length >= 4)
        {
            if (current.Contains(originalTitle, StringComparison.OrdinalIgnoreCase) ||
                originalTitle.Contains(current, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Window title used by external now-playing detectors. Keep the raw filename here:
    /// parsed display metadata can lose release/season/episode details that Anitomy needs.
    /// </summary>
    public string TrackingTitle
    {
        get
        {
            var filename = System.IO.Path.GetFileNameWithoutExtension(VideoUrl);
            if (!string.IsNullOrWhiteSpace(filename))
                return $"[KirihaPlayer] {filename}";

            var title = !string.IsNullOrEmpty(AnimeTitleRomaji)
                ? AnimeTitleRomaji
                : (!string.IsNullOrEmpty(AnimeTitleEn) ? AnimeTitleEn : AnimeTitleRu);
            return $"[KirihaPlayer] {title}";
        }
    }

    public bool UseRussianTitles => _settingsService?.Current.UI.UseRussianTitles ?? false;

    public string TopTitle
    {
        get
        {
            if (UseRussianTitles && !string.IsNullOrWhiteSpace(AnimeTitleRu))
                return AnimeTitleRu;

            if (!string.IsNullOrWhiteSpace(AnimeTitleRomaji))
                return AnimeTitleRomaji;

            if (!string.IsNullOrWhiteSpace(AnimeTitleEn))
                return AnimeTitleEn;

            return !string.IsNullOrWhiteSpace(AnimeTitleRu) ? AnimeTitleRu : AnimeTitle;
        }
    }

    public string BottomTitle
    {
        get
        {
            var top = TopTitle;

            if (UseRussianTitles && !string.IsNullOrWhiteSpace(AnimeTitleRu))
            {
                if (!string.IsNullOrWhiteSpace(AnimeTitleEn) && !string.Equals(AnimeTitleEn, top, StringComparison.OrdinalIgnoreCase))
                    return AnimeTitleEn;

                if (!string.IsNullOrWhiteSpace(AnimeTitleRomaji) && !string.Equals(AnimeTitleRomaji, top, StringComparison.OrdinalIgnoreCase))
                    return AnimeTitleRomaji;

                return string.Empty;
            }

            if (!string.IsNullOrWhiteSpace(AnimeTitleEn) && !string.Equals(AnimeTitleEn, top, StringComparison.OrdinalIgnoreCase))
                return AnimeTitleEn;

            if (!string.IsNullOrWhiteSpace(AnimeTitleRu) && !string.Equals(AnimeTitleRu, top, StringComparison.OrdinalIgnoreCase))
                return AnimeTitleRu;

            return string.Empty;
        }
    }

    public bool HasBottomTitle => !string.IsNullOrEmpty(BottomTitle);
    public bool HasEpisodeAndBottom => !string.IsNullOrEmpty(EpisodeTitle) && HasBottomTitle;

    partial void OnAnimeTitleRuChanged(string value)
    {
        OnPropertyChanged(nameof(TopTitle));
        OnPropertyChanged(nameof(BottomTitle));
        OnPropertyChanged(nameof(HasBottomTitle));
        OnPropertyChanged(nameof(HasEpisodeAndBottom));
    }

    partial void OnAnimeTitleEnChanged(string value)
    {
        OnPropertyChanged(nameof(TopTitle));
        OnPropertyChanged(nameof(BottomTitle));
        OnPropertyChanged(nameof(HasBottomTitle));
        OnPropertyChanged(nameof(HasEpisodeAndBottom));
    }

    partial void OnAnimeTitleRomajiChanged(string value)
    {
        OnPropertyChanged(nameof(TopTitle));
        OnPropertyChanged(nameof(BottomTitle));
        OnPropertyChanged(nameof(HasBottomTitle));
        OnPropertyChanged(nameof(HasEpisodeAndBottom));
    }

    partial void OnEpisodeTitleChanged(string value)
    {
        OnPropertyChanged(nameof(HasEpisodeAndBottom));
    }
}
