<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Kiriha.Core.Abstractions\Kiriha.Core.Abstractions.csproj" />
    <ProjectReference Include="..\Kiriha.Infrastructure\Kiriha.Infrastructure.csproj" />
    <ProjectReference Include="..\Kiriha.Core.Domain\Kiriha.Core.Domain.csproj" />
    
  </ItemGroup>

  <ItemGroup>
    
    <PackageReference Include="Serilog" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="System.Threading.RateLimiting" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <UseWPF Condition="$(TargetFramework.Contains('-windows'))">true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\**\*" />
  </ItemGroup>

</Project>

