<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Kiriha.Core.Abstractions\Kiriha.Core.Abstractions.csproj" />
    <ProjectReference Include="..\Kiriha.Core\Kiriha.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="System.Threading.RateLimiting" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net10.0;net10.0-windows10.0.19041.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWPF Condition="$(TargetFramework.Contains('-windows'))">true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\**\*" />
  </ItemGroup>

</Project>
