using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace Kiriha.Services.Data;

/// <summary>
/// Owns the schema lifecycle of the SQLite database. Strategy:
///   * <see cref="RelationalDatabaseFacadeExtensions.MigrateAsync"/> applies
///     EF migrations from <c>Services/Data/Migrations</c>. The model is the
///     single source of truth (<see cref="AppDbContext.OnModelCreating"/>);
///     migrations are auto-generated via <c>dotnet ef migrations add</c>.
///   * One-shot adoption for legacy DBs created by <c>EnsureCreated</c>
///     before migrations existed: we detect the missing
///     <c>__EFMigrationsHistory</c> table and stamp it with the initial
///     migration row, so <see cref="RelationalDatabaseFacadeExtensions.MigrateAsync"/>
///     treats the existing schema as already-applied instead of trying to
///     re-create tables and failing.
///   * WAL pragmas applied in a single batched statement (one round-trip on
///     cold start). <c>synchronous=NORMAL</c> is the safe-default for WAL —
///     durable across process kill — and <c>wal_autocheckpoint=200</c> caps
///     how much the WAL can outgrow the main file before being folded back.
/// </summary>
public sealed class DatabaseInitializer
{
    /// <summary>
    /// Migration ID of the baseline schema (auto-generated by
    /// <c>dotnet ef migrations add InitialCreate</c>). Used to stamp legacy
    /// EnsureCreated-style DBs into the migrations history on first launch.
    /// </summary>
    private const string InitialMigrationId = "20260430184034_InitialCreate";

    private readonly IDbContextFactory<AppDbContext> _contextFactory;
    private readonly TaskCompletionSource _initTcs = new(TaskCreationOptions.RunContinuationsAsynchronously);
    private int _initStarted; // 0 = not started, 1 = started (Interlocked guard)

    public Task InitializationTask => _initTcs.Task;

    public DatabaseInitializer(IDbContextFactory<AppDbContext> contextFactory)
    {
        _contextFactory = contextFactory;
    }

    public async Task InitializeAsync()
    {
        // Single-shot guard: every concurrent caller awaits the same TCS.
        if (Interlocked.CompareExchange(ref _initStarted, 1, 0) != 0)
        {
            await _initTcs.Task;
            return;
        }

        try
        {
            await Task.Run(async () =>
            {
                using var context = await _contextFactory.CreateDbContextAsync();

                await AdoptLegacyEnsureCreatedDatabaseAsync(context);
                await context.Database.MigrateAsync();

                // WAL + sane defaults in a single batch (one round-trip on cold start).
                await context.Database.ExecuteSqlRawAsync(
                    "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA wal_autocheckpoint=200;");

                Log.Information("Database initialized");
            });
            _initTcs.TrySetResult();
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to initialize EF Core database");
            _initTcs.TrySetException(ex);
        }
    }

    /// <summary>
    /// Detects DBs created by the previous <c>EnsureCreated</c>-based code path
    /// and stamps them with the baseline migration so the upcoming
    /// <see cref="RelationalDatabaseFacadeExtensions.MigrateAsync"/> sees the
    /// schema as already-applied. Idempotent: a no-op when the history table
    /// already exists or when the DB is brand-new (no <c>user_anime</c> table
    /// either).
    /// </summary>
    private static async Task AdoptLegacyEnsureCreatedDatabaseAsync(AppDbContext context)
    {
        // sqlite_master is the canonical place to check for table existence — cheaper
        // than a probe SELECT and works on a fresh connection without prepared-statement
        // caching surprises.
        var historyExists = await TableExistsAsync(context, "__EFMigrationsHistory");
        if (historyExists) return;

        var userAnimeExists = await TableExistsAsync(context, "user_anime");
        if (!userAnimeExists)
        {
            // Fresh DB: MigrateAsync will create everything including the history table.
            return;
        }

        Log.Information("DatabaseInitializer: legacy EnsureCreated DB detected; stamping with {Migration}", InitialMigrationId);
        await context.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS ""__EFMigrationsHistory"" (
                ""MigrationId"" TEXT NOT NULL CONSTRAINT ""PK___EFMigrationsHistory"" PRIMARY KEY,
                ""ProductVersion"" TEXT NOT NULL
            );");
        await context.Database.ExecuteSqlRawAsync(
            @"INSERT OR IGNORE INTO ""__EFMigrationsHistory"" (""MigrationId"", ""ProductVersion"") VALUES ({0}, {1});",
            InitialMigrationId, typeof(DbContext).Assembly.GetName().Version?.ToString() ?? "10.0.0");
    }

    private static async Task<bool> TableExistsAsync(AppDbContext context, string tableName)
    {
        var conn = context.Database.GetDbConnection();
        if (conn.State != System.Data.ConnectionState.Open)
            await conn.OpenAsync();
        using var cmd = conn.CreateCommand();
        cmd.CommandText = "SELECT COUNT(1) FROM sqlite_master WHERE type='table' AND name = $name;";
        var p = cmd.CreateParameter();
        p.ParameterName = "$name";
        p.Value = tableName;
        cmd.Parameters.Add(p);
        var result = await cmd.ExecuteScalarAsync();
        return System.Convert.ToInt64(result) > 0;
    }

    /// <summary>
    /// Forces all pending WAL frames into the main database file. Call before
    /// app exit and on system session-end to guarantee durability against a
    /// forced <c>TerminateProcess</c>.
    /// </summary>
    public async Task FlushAsync()
    {
        try
        {
            using var context = await _contextFactory.CreateDbContextAsync();
            await context.Database.ExecuteSqlRawAsync("PRAGMA wal_checkpoint(TRUNCATE);");
            Log.Information("DatabaseInitializer: WAL checkpoint(TRUNCATE) completed");
        }
        catch (Exception ex)
        {
            Log.Error(ex, "DatabaseInitializer: FlushAsync failed");
        }
    }
}
