<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="DiscordRichPresence" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kiriha.Core.Abstractions\Kiriha.Core.Abstractions.csproj" />
    <ProjectReference Include="..\Kiriha.Core.Domain\Kiriha.Core.Domain.csproj" />
    
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Tracking\Anisthesia\players.anisthesia" />
  </ItemGroup>

</Project>

